### PR TITLE
New catalan and spanish translations

### PR DESCRIPTION
**Pull request by innocent-de-marchi**
Hi Sérgio,

I send the translations to catalan and spanish to attach to the project.

Regards!

I. De Marchi
[ca-es-po-files.tar.gz](https://github.com/rzr/pinball/files/1856988/ca-es-po-files.tar.gz)

### CODE REVIEW

**Comment by rzr** [comment]
hi thank you for the contrib but upstream is on sf.net, I wish I can give maintainer right as soon as we manage to build tables out of main project then we'll can merge patches like yours ?

**Comment by innocent-de-marchi** [comment]
Hi Philippe Coval,

> hi thank you for the contrib but upstream is on sf.net, I wish I can
> give maintainer right as soon as we manage to build tables out of
> main project then we'll can merge patches like yours ?

So do you plan to continue updating the sf.net repository? Recently, I
have adopatado the pinball package in Debian. Now I am in contact with
Sérgio Basto (sergiomb2) to incorporate several patches that solve bug
reports in Debian: I have made this request at the suggestion of Sérgio.

Regards!

I. De Marchi

**Comment by rzr** [comment]
official upstream is in SF.net and I am (unactive) maintainer, so I am ok to give this role, to the one that manage to rebuild extra tables outside sources (using pinconfig), this way development of tables and engine can be done in parallel and project can scale at higher level.

**Comment by innocent-de-marchi** [comment]
Hi Philippe Coval,

> official upstream is in SF.net and I am (unactive) maintainer, so I
> am ok to give this role, to the one that manage to rebuild extra
> tables outside sources (using pinconfig), this way development of
> tables and engine can be done in parallel and project can scale at
> higher level.
> 
OK. But then, the publication of new versions by Sérgio Bastos [0], can
they be considered official versions? On sf, no official version
has been published since 0.3.1, but there are changes like the
translation or the new hurd table. In the version of Sérgio there is
the translation into Portuguese and French, and new tables, and some
changes in the code, and some changes in the code that fix bugs
reported in Debian. All are program improvements, but can they be
published as an official version? Will the sf version and the Sérgio
version be merged?

Regards!

I. De Marchi

[0] https://github.com/sergiomb2/pinball/releases

**Comment by rzr** [comment]
Building out of sources is top priority before maintainership change (and then next release).

**Comment by sergiomb2** [comment]
> official upstream is in SF.net and I am (unactive) maintainer, so I am ok to give this role, to the one that
> manage to rebuild extra tables outside sources (using pinconfig), this way development of tables and 
> engine can be done in parallel and project can scale at higher level.

yeah , finally I understood you , but I don't know do that . 

innocent-de-marchi  , you have done one pull request from my repo to this repo , to you do a PR (pull request) you need fork my repo ( or this one ) , change the code in your repo ( not send thing in attach ) and do the pull request with source code updated it . 

:) 

rzr , unfortunately And don't have much time , I even not finish all things in "my" project still have professor2 table to finish , but I will try

**Comment by rzr** [comment]
Please try it is critical for project sustainability

**Comment by rzr** [comment]
Relate-to: https://github.com/rzr/pinball/issues/4

**Comment by rzr** [comment]
Please isolate changes in separates PR 

Regards

**Comment by rzr** [comment]
Please rebase, I am considering to release a new version soon or later

**Comment by rzr** [comment]
hi @innocent-de-marchi I plan to adopt pinball debian package and release a version for pincab setup
I plan to reset master to this one
https://github.com/rzr/pinball/tree/next/devel/master

**Pull request closed without merging**
