### PR TITLE
Apply keyboard config patch from https://github.com/sergiomb2/pinball…

### PR DESCRIPTION
**Pull request by limburgher**
…/commit/6d222fcdbf2238c16198a4bbcdf1b9afaea8a187

### CODE REVIEW

**Comment by limburgher** [comment]
I don't believe I can edit the commit message once pushed.

**Comment by rzr** [comment]
git commit --amend and git push --force your branch

**Comment by limburgher** [comment]
Done.

**Comment by rzr** [comment]
I see original change is:
https://github.com/sergiomb2/pinball/commit/6d222fcdbf2238c16198a4bbcdf1b9afaea8a187.patch
maybe I can apply it as it is and link to this PR

**Pull request merged**
